### ISSUE TITLE
Localize CSS

### ISSUE THREAD

**Issue by papandreou** [assetgraph/assetgraph-builder#29]
Clone the asset for each locale and remove or keep CSS rules whose selectors match on `<html lang="...">`.

For American English that would turn

``` css
html[lang="en"] .myThing { width: 123px; }
```

into

``` css
.myThing { width: 123px; }
```

... but for non-English locales the rule would be removed.

Maybe also add a syntax for localizing the `content` property.

Any other ideas?
